# Js Section Defaults
js:
  files: []
  header: |
    /*! Company Name http://www.company-website.com <%= bundle.name %>.js <%= bundle.version %> <%= bundle[section-name].md5 %> */
  buildDir: some/path/to/build/path
  docTask: name-of-documentation-task-here
  concatTask: name-of-concat-task-here
  minTask: minify-task-name-here
  lintTask: lint-task-name-here

# Html Section Defaults
html:
  files: []
  header: |
    <!-- Company Name http://www.company-website.com <%= bundle.name %>.html <%= bundle.version %> <%= bundle[section-name].md5 %> -->
  buildDir: some/path/to/build/path
  docTask: name-of-documentation-task-here
  concatTask: name-of-concat-task-here
  minTask: minify-task-name-here
  lintTask: lint-task-name-here

# Css Section Defaults
css:
  files: []
  header: |
    /*! Company Name http://www.company-website.com <%= bundle.name %>.css <%= bundle.version %> <%= bundle[section-name].md5 %> */
  buildDir: some/path/to/build/path
  docTask: name-of-documentation-task-here
  concatTask: name-of-concat-task-here
  minTask: minify-task-name-here
  lintTask: lint-task-name-here

jsmin:
  artifactPreSuffix: ".min"

# Watch Task Defaults
watch:
  tasks:
    - build
    - compass
    - deploy
  flags:
    dev: false

images:
  files: []

# RequireJs Defaults
requirejs: null

# Browserify Defaults
browserify: null

# Build Task
build:

  # Tasks to run if task is not overwritten by flag (see flags below)
  tasks:
    - concat
    - css
    - requirejs
    - browserify

  # This is a global lint flag that is used if there is a lint task specified for a section
  lintBeforeBuild: true

  # Concatenate files if files exists
  concatFiles: false

  # Runs require js section if exists
  runRequireJs: true

  # Runs browserify section if exists
  runBrowserify: true

# Deploy Task
deploy:

  # Files to be deployed
  files: []

  # Global deploy artifacts flag (used if no `deployArtifact` field is found for a section in this config
  deployArtifacts: true

  # Whether or not to deploy artifact files that aren't minified or that do not have the ".min" pre-suffix
  deployPreArifacts: false

  # Flag which determines whether or not to automatically deploy file arrays
  deployFiles: false

  # Should files be linted before deploy
  lintBeforeDeploy: false
